### PR TITLE
Upgrade docker-compose.yml to v3 and network spec to 'best practice'

### PR DESCRIPTION
**Pull request by RichardBruskiewich**
The current docker-tripal docker-compose.yml file uses the "links" directive for networking, which is somewhat deprecated (see https://docs.docker.com/compose/compose-file/#links).  This pull request updates the docker-compose.yml to comply with the recommendation to use the "networks" directives instead. Along the way, the docker-compose.yml version is set to version "3". The web "depends_on" directive was added for good measure to encourage proper sequencing in the build deployment.

Testing this revised docker-compose.yml file, it seems to still work fine with the new directives.

### CODE REVIEW

**Comment by abretaud** [comment]
Thanks @RichardBruskiewich!
Why not rename the db container to 'postgres'? It would allow to get rid of the network definition as bridge is already the default mode

**Comment by RichardBruskiewich** [comment]
@abretaud sure, fine by me.  I'll do that and retest. The point is that  the "links" specification is deprecated. A simpler (default) network specification makes sense here.

**Comment by abretaud** [comment]
> @abretaud sure, fine by me. I'll do that and retest. The point is that the "links" specification is deprecated. A simpler (default) network specification makes sense here.

Yes, I'm fine with replacing `links` by `depends_on`, it's just that [defining the network](https://github.com/erasche/docker-tripal/pull/29/files#diff-4e5e90c6228fd48698d074241c2ba760R46) and [specifying it](https://github.com/erasche/docker-tripal/pull/29/files#diff-4e5e90c6228fd48698d074241c2ba760R22) would not be needed if the db container [was just renamed postgres](https://github.com/erasche/docker-tripal/pull/29/files#diff-4e5e90c6228fd48698d074241c2ba760R25). I like to keep only necessary code ;)

**Comment by RichardBruskiewich** [comment]
Hi Anthony, 

see my latest commit to my fork of v3.x. I've taken all of your advice - renamed 'db' to 'postgres' and removing explicit networking since it is "bridge implied" using service tags as Docker network hostnames of the containers.  The "depends_on" is more of a container startup sequencing dependency directive (not related to networking).  I did test a comparable build - works fine.  Over to you to process the pull request now!

**Comment by abretaud** [comment]
Thank you @RichardBruskiewich !

**Pull request merged**
